sudo usermod -aG docker ec2-user
groups ec2-user
mkdir project-df
cd project-df
vi Dockerfile

# Use the official Ubuntu base image
FROM ubuntu:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update package repositories and install necessary packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Create a directory for our app
WORKDIR /app

# Copy index.html /app/

# Expose port 3001 for the web server
EXPOSE 3001

# Command to run the Python web server
CMD ["python3", "-m", "http-server", "3001"]

vi index.html

<!DOCTYPE html>
<html>
<head>
    <title>Dockerfile Demo</title>
</head>
<body>
<h1>Hello Friends,</h1>
<p>Welcome to my Channel!</p>
<p>Make sure to Like & Subscribe</p>
<p>Thank you</p>
</body>
</html>




docker build -t ubuntu-docker-example .
docker ps -a (display container - process status)
docker run -d -p 3001:3001 --name ubuntu-container ubintu-docker-example
docker ps -a


